---
# defaults file for sysutil

sysutil_bin_state: present
sysutil_url: https://github.com/Giftpilz0/sysutil/releases/download/{{ sysutil_tag }}/sysutil_{{ sysutil_tag }}_linux_{{ sysutil_arch }}.tar.gz
sysutil_arch: amd64
sysutil_tag: 1.3.0
sysutil_path: /usr/local/bin
